[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false
cursor = { text = "#08132e", cursor = "#7685a3" }
vi_mode_cursor = { text = "#08132e", cursor = "#af85ad" }
line_indicator = { foreground = "#fefefe", background = "#08132e" }
footer_bar = { foreground = "#08132e", background = "#fefefe" }
selection = { text = "#08132e", background = "#7685a3" }

[colors.primary]
background = "#08132e"
foreground = "#fefefe"
dim_foreground = "#5c6375"
bright_foreground = "#ffffff"

[colors.search]
matches = { foreground = "#08132e", background = "#9781a5" }
focused_match = { foreground = "#08132e", background = "#7685a3" }

[colors.hints]
start = { foreground = "#08132e", background = "#af85ad" }
end = { foreground = "#08132e", background = "#9781a5" }

[colors.normal]
black = "#797f8e"
red = "#eec7de"
green = "#708fc0"
yellow = "#47b1ea"
blue = "#7685a3"
magenta = "#af85ad"
cyan = "#9781a5"
white = "#fefefe"

[colors.bright]
black = "#8f96a5"
red = "#fde2f2"
green = "#86a6d9"
yellow = "#71c8fb"
blue = "#8c9cbb"
magenta = "#c79cc5"
cyan = "#ae98bd"
white = "#ffffff"

[colors.dim]
black = "#5c6274"
red = "#a08aa2"
green = "#4d658e"
yellow = "#327baa"
blue = "#56637f"
magenta = "#765e82"
cyan = "#685e7e"
white = "#aaaeb7"

[[colors.indexed_colors]]
index = 16
color = "#47b1ea"
[[colors.indexed_colors]]
index = 17
color = "#eec7de"
