[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false
cursor = { text = "#01231b", cursor = "#52959b" }
vi_mode_cursor = { text = "#01231b", cursor = "#3ebcf7" }
line_indicator = { foreground = "#fdffff", background = "#01231b" }
footer_bar = { foreground = "#01231b", background = "#fdffff" }
selection = { text = "#01231b", background = "#52959b" }

[colors.primary]
background = "#01231b"
foreground = "#fdffff"
dim_foreground = "#576e69"
bright_foreground = "#feffff"

[colors.search]
matches = { foreground = "#01231b", background = "#4a8ff8" }
focused_match = { foreground = "#01231b", background = "#52959b" }

[colors.hints]
start = { foreground = "#01231b", background = "#3ebcf7" }
end = { foreground = "#01231b", background = "#4a8ff8" }

[colors.normal]
black = "#748b85"
red = "#85eec0"
green = "#2eae38"
yellow = "#7dd4e9"
blue = "#52959b"
magenta = "#3ebcf7"
cyan = "#4a8ff8"
white = "#fdffff"

[colors.bright]
black = "#8aa29c"
red = "#b9fddd"
green = "#4cc651"
yellow = "#a0ebfe"
blue = "#69acb2"
magenta = "#87d1fa"
cyan = "#73a9fb"
white = "#feffff"

[colors.dim]
black = "#546e67"
red = "#58a988"
green = "#1f7f2e"
yellow = "#5398a3"
blue = "#3a7172"
magenta = "#2988ac"
cyan = "#316aad"
white = "#a7b4b1"

[[colors.indexed_colors]]
index = 16
color = "#7dd4e9"
[[colors.indexed_colors]]
index = 17
color = "#85eec0"
