#!/usr/bin/env python3
"""Keep Rofi's palette aligned with Polybar's generated colors."""

from configparser import ConfigParser
from pathlib import Path
import sys


def main() -> None:
    source, target = map(Path, sys.argv[1:3])
    config = ConfigParser(interpolation=None)
    if not config.read(source) or not config.has_section("colors"):
        raise SystemExit(f"No [colors] section in {source}")

    names = (
        "background",
        "background-alt",
        "foreground",
        "disabled",
        "primary",
        "secondary",
        "alert",
    )
    lines = ["/* Generated by colourme. */", "* {"]
    lines.extend(f"    colourme-{name}: {config.get('colors', name)};" for name in names)
    lines.extend(["}", ""])
    content = "\n".join(lines)
    if not target.exists() or target.read_text() != content:
        target.write_text(content)


if __name__ == "__main__":
    main()
